spring.profiles.active=${APP_PROFILE:test}
spring.jpa.open-in-view=false
jwt.secret-key=427408a1-84c9-2007-bb1c-6cced202f5a7
#server.servlet.context-path=/rest
#spring.profiles.active=dev --> para criar o arquivo create.sql